Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,7 +81,15 @@ jobs:
        DRAFT_RELEASE: false
      with:
        args: download/*.zip
-
+       
+# read version number from changelog.md
+   - name: check changelog
+     id: check_changelog
+     run: |
+        [ -f CHANGELOG.md ] || ( echo "::error::File CHANGELOG.md not found!" && false )
+        IMAGE_VERSION=$(grep '##' CHANGELOG.md | head -n 1 | cut -d ' ' -f 2)
+        echo "IMAGE_VERSION: $IMAGE_VERSION"
+        
 # create a new pre-released version
    - name: Pre-Release
      if: ( ! startsWith(github.ref, 'refs/tags/v') )
