Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,9 +59,28 @@ jobs:
      run: |
           echo "[C] github.ref: ${{github.ref}}"
 
+# This action checks CHANGELOG.md for current version of project
+# This version read from CHANGELOG.md file and send as a release name 
+   - name: Get_version_Changelog
+     id: Get_version_Changelog
+     run: |
+        [ -f CHANGELOG.md ] || ( echo "::error::File CHANGELOG.md not found!" && false )
+        TAG_NAME=$(grep '##' CHANGELOG.md | head -n 1 | cut -d ' ' -f 2 )
+        if [[ $TAG_NAME != *[{}\(\)\[\]]* ]]  
+        then
+          echo "::error::File CHANGELOG.md version without square bracket!" && false
+        else
+          TAG_NAME1=${TAG_NAME:1:-1}
+          echo "TAG_NAME1: $TAG_NAME1"
+          echo "TAG_NAME1=$TAG_NAME1" >> "$GITHUB_ENV"
+          FirstCharcter=${TAG_NAME1:0:1}
+          echo "FirstCharcter: $FirstCharcter"
+          echo "FirstCharcter=$FirstCharcter" >> "$GITHUB_ENV"
+        fi
+
    - name: Delete last Pre-Release
-     if: ( ! startsWith(github.event.ref, 'refs/tags/v'))
-#     if: ${{ env.FirstCharcter != 'v' }}
+#     if: ( ! startsWith(github.event.ref, 'refs/tags/v'))
+     if: ${{ env.FirstCharcter != 'v' }}
      uses: docker://antonyurchenko/git-release:latest
      env:
        RELEASE_NAME: "Latest"
@@ -73,7 +92,8 @@ jobs:
 
 # Delete the last "latest" release version tag (and not pre-released one) if exists
    - name: Delete tag latest
-     if: ( ! startsWith(github.event.ref, 'refs/tags/v'))
+      if: ${{ env.FirstCharcter != 'v' }}
+#     if: ( ! startsWith(github.event.ref, 'refs/tags/v'))
      run: (git tag -d latest && git push origin :refs/tags/latest) || true
 
 # create a new released version
@@ -83,8 +103,9 @@ jobs:
      if: (startsWith(github.event.ref, 'refs/tags/v'))
      uses: docker://antonyurchenko/git-release:latest
      env:
-#       RELEASE_NAME: 0.0.9
-#       UNRELEASED_TAG: "${{ env.TAG_NAME1 }}"
+       RELEASE_NAME: "${{ env.TAG_NAME1 }}"
+       UNRELEASED: update
+       UNRELEASED_TAG: "${{ env.TAG_NAME1 }}"
        PRE_RELEASE: false
        DRAFT_RELEASE: false
      with:
